[package]
name = "quick-find-core"
version = "0.1.0"
edition = "2024"

[dependencies]
walkdir = "2.5.0"
glob = "0.3.2"
rayon = "1.10.0"
tempfile = "3.20.0"
serde = { version = "1.0.219", features = ["derive"] }

pandorust-core = { path = "../pandorust-core" }